"""Add missing tables

Revision ID: a2fff788213c
Revises: e736e67f7c35
Create Date: 2026-08-09 21:23:43.352708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2fff788213c'
down_revision: Union[str, Sequence[str], None] = 'e736e67f7c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cover_bg_path', sa.String(), nullable=True),
    sa.Column('body_bg_path', sa.String(), nullable=True),
    sa.Column('cta_bg_path', sa.String(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.Column('style_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carousel_templates_id'), 'carousel_templates', ['id'], unique=False)
    op.add_column('raw_articles', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_articles', 'image_url')
    op.drop_index(op.f('ix_carousel_templates_id'), table_name='carousel_templates')
    op.drop_table('carousel_templates')
    # ### end Alembic commands ###
